<?php

namespace ContainerZZleL1B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lg_0VSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lg.0V_S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lg.0V_S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'answer' => ['privates', '.errored..service_locator.Lg.0V_S.App\\Entity\\Answer', NULL, 'Cannot autowire service ".service_locator.Lg.0V_S": it needs an instance of "App\\Entity\\Answer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'answer' => 'App\\Entity\\Answer',
        ]);
    }
}
