controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_auth_login:
    path: '/api/login'
    controller: 'App\Controller\Api\AuthController::login'