<?php

namespace ContainerLbzbTPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnswer2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Lg.0V_S.App\Entity\Answer' shared service.
     *
     * @return \App\Entity\Answer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Lg.0V_S": it needs an instance of "App\\Entity\\Answer" but this type has been excluded in "config/services.yaml".');
    }
}
