<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLbzbTPr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLbzbTPr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLbzbTPr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLbzbTPr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLbzbTPr\App_KernelDevDebugContainer([
    'container.build_hash' => 'LbzbTPr',
    'container.build_id' => '7272ab32',
    'container.build_time' => 1707406572,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLbzbTPr');
