<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZZleL1B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZZleL1B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZZleL1B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZZleL1B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZZleL1B\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZZleL1B',
    'container.build_id' => '50e0b691',
    'container.build_time' => 1707402799,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZZleL1B');
